/**
 * AFLO domain event catalog (client-lifecycle foundation, slice A).
 *
 * The canonical list of lifecycle events the platform emits. Names are
 * PascalCase business facts in the past tense. Every event flows through the
 * PostgreSQL outbox (DATABASE_SCHEMA.md §9.4) — no external broker in V1.
 */

export const EVENT_TYPES = [
  "LeadCreated",
  "LeadStatusChanged",
  "IntakeStarted",
  "IntakeSectionCompleted",
  "IntakeCompleted",
  "ClientActivated",
  "FinancialProfileUpdated",
  "CreditProfileUpdated",
  "GoalCreated",
  "ReadinessAssessed",
  "RoadmapDrafted",
  "RoadmapApproved",
  "RoadmapPublished",
  "MilestoneActivated",
  "TaskAssigned",
  "TaskCompleted",
  "DocumentRequested",
  "DocumentUploaded",
  "DocumentReviewed",
  "AppointmentScheduled",
  "EngagementRiskDetected",
  "ProgressReportGenerated",
  "ProgressReportPublished",
  "EducationAssigned",
  "EducationCompleted",
  "PartnerReferralCreated",
  "ConsentGranted",
  "ConsentRevoked",
  "MessagePosted",
  "MessageRead",
  // Human Review Center + Playbooks + Workflow Discovery (Workstream A PR-5).
  // Payloads carry ids/digests/reason codes ONLY — never artifact bodies.
  "ReviewItemCreated",
  "ReviewItemSubmitted",
  "ReviewDecisionRecorded",
  "ReviewItemPublished",
  "ReviewItemSuperseded",
  "ReviewItemWithdrawn",
  "ReviewOutcomeRecorded",
  "PlaybookVersionSaved",
  "PlaybookVersionPublished",
  "WorkflowDiscoveryRaised",
  "WorkflowDiscoveryResolved",
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

/** Aggregate kinds an event may attach to. */
export const AGGREGATE_TYPES = [
  "lead",
  "client",
  "financial_profile",
  "credit_profile",
  "goal",
  "readiness_assessment",
  "roadmap",
  "milestone",
  "task",
  "document",
  "appointment",
  "report",
  "education_assignment",
  "referral",
  "consent",
  "conversation",
  "review_item",
  "playbook",
  "workflow_discovery_item",
] as const;

export type AggregateType = (typeof AGGREGATE_TYPES)[number];

/** The aggregate type each event must attach to — validated at creation. */
export const EVENT_AGGREGATE: Record<EventType, AggregateType> = {
  LeadCreated: "lead",
  LeadStatusChanged: "lead",
  IntakeStarted: "client",
  IntakeSectionCompleted: "client",
  IntakeCompleted: "client",
  ClientActivated: "client",
  FinancialProfileUpdated: "financial_profile",
  CreditProfileUpdated: "credit_profile",
  GoalCreated: "goal",
  ReadinessAssessed: "readiness_assessment",
  RoadmapDrafted: "roadmap",
  RoadmapApproved: "roadmap",
  RoadmapPublished: "roadmap",
  MilestoneActivated: "milestone",
  TaskAssigned: "task",
  TaskCompleted: "task",
  DocumentRequested: "document",
  DocumentUploaded: "document",
  DocumentReviewed: "document",
  AppointmentScheduled: "appointment",
  EngagementRiskDetected: "client",
  ProgressReportGenerated: "report",
  ProgressReportPublished: "report",
  EducationAssigned: "education_assignment",
  EducationCompleted: "education_assignment",
  PartnerReferralCreated: "referral",
  ConsentGranted: "consent",
  ConsentRevoked: "consent",
  MessagePosted: "conversation",
  MessageRead: "conversation",
  ReviewItemCreated: "review_item",
  ReviewItemSubmitted: "review_item",
  ReviewDecisionRecorded: "review_item",
  ReviewItemPublished: "review_item",
  ReviewItemSuperseded: "review_item",
  ReviewItemWithdrawn: "review_item",
  ReviewOutcomeRecorded: "review_item",
  PlaybookVersionSaved: "playbook",
  PlaybookVersionPublished: "playbook",
  WorkflowDiscoveryRaised: "workflow_discovery_item",
  WorkflowDiscoveryResolved: "workflow_discovery_item",
};

/**
 * Per-type schema version. Bump when a payload shape changes incompatibly;
 * consumers use (event_type, event_version) to select a decoder. All types
 * start at 1.
 */
export const EVENT_VERSIONS: Record<EventType, number> = {
  LeadCreated: 1,
  LeadStatusChanged: 1,
  IntakeStarted: 1,
  IntakeSectionCompleted: 1,
  IntakeCompleted: 1,
  ClientActivated: 1,
  FinancialProfileUpdated: 1,
  CreditProfileUpdated: 1,
  GoalCreated: 1,
  ReadinessAssessed: 1,
  RoadmapDrafted: 1,
  RoadmapApproved: 1,
  RoadmapPublished: 1,
  MilestoneActivated: 1,
  TaskAssigned: 1,
  TaskCompleted: 1,
  DocumentRequested: 1,
  DocumentUploaded: 1,
  DocumentReviewed: 1,
  AppointmentScheduled: 1,
  EngagementRiskDetected: 1,
  ProgressReportGenerated: 1,
  ProgressReportPublished: 1,
  EducationAssigned: 1,
  EducationCompleted: 1,
  PartnerReferralCreated: 1,
  ConsentGranted: 1,
  ConsentRevoked: 1,
  MessagePosted: 1,
  MessageRead: 1,
  ReviewItemCreated: 1,
  ReviewItemSubmitted: 1,
  ReviewDecisionRecorded: 1,
  ReviewItemPublished: 1,
  ReviewItemSuperseded: 1,
  ReviewItemWithdrawn: 1,
  ReviewOutcomeRecorded: 1,
  PlaybookVersionSaved: 1,
  PlaybookVersionPublished: 1,
  WorkflowDiscoveryRaised: 1,
  WorkflowDiscoveryResolved: 1,
};
